import '@/app/styles/globals.css';
import { Providers } from './providers';

export const metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
};
//wena papu!!!!!!!!!!!!!!!

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
